name: App2-iOS
options:
  bundleIdPrefix: fr.lunettesvr
  deploymentTarget:
    iOS: "16.0"
targets:
  App2VR:
    type: application
    platform: iOS
    sources:
      - Sources
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: Kyoh Productions
        CFBundleName: Kyoh Productions
        UILaunchScreen: {}
        UIRequiresFullScreen: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: fr.lunettesvr.app2vr
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGN_STYLE: Manual
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGN_IDENTITY: ""
        DEVELOPMENT_TEAM: ""
